name: Java CI/CD with Docker & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Build Docker image
      run: docker build -t gradle-java-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # Docker Image
      
    - name: Push Docker image
      run: |
        docker tag gradle-java-app ${{ secrets.DOCKER_USERNAME }}/gradle-java-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/gradle-java-app:latest
        
#Connection to your VM Ubuntu ..................... ......
    - name: Deploy to Ubuntu VM
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/gradle-java-app:latest
          docker stop gradle-java-app || true
          docker rm gradle-java-app || true
          docker run -d -p 8080:8080 --name gradle-java-app ${{ secrets.DOCKER_USERNAME }}/gradle-java-app:latest

